Fix check update issue
Removed the unnecessary comma at the end of line 60 causing a malformed json exception.

[17:18:25] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [bigreactors] Starting version check at https://raw.githubusercontent.com/ZeroNoRyouki/ExtremeReactors2/master/update.json
[17:18:25] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 61 column 6 path $..1.17.1-2.0.30
        at com.google.gson.Gson.fromJson(Gson.java:902) ~[server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:195) ~[forge:?] {re:classloading}
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_212] {}
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:139) [forge:?] {re:classloading}
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 61 column 6 path $..1.17.1-2.0.30
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:69) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.16.5-20210115.111550-extra.jar:?] {re:mixin}
        ... 6 more